spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/course_system?currentSchema=course_path
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  redis:
    timeout: 3000
    host: 43.142.36.30
    password: BXYbxy523656497
    port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: false
      logic-delete-value: true
